version: '3'
services:
  back-end:
    build:
      context: ./Back-End/
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "5000:5000"

  front-end:
    build:
      context: ./Front-End/
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 80:80
